import { Sparkles } from 'lucide-react';
import { MarkdownContent } from '@/components/MarkdownContent';

export function ProposalAiSummary({ summary }: { summary: string | null }) {
  if (!summary) return null;

  return (
    <div className="rounded-r-lg border-l-2 border-primary/40 p-3 bg-primary/5">
      <div className="flex items-center gap-1.5 mb-1.5">
        <Sparkles className="h-3.5 w-3.5 text-primary" />
        <span className="text-xs font-semibold text-primary">AI Summary</span>
      </div>
      <MarkdownContent content={summary} className="text-sm leading-relaxed" />
      <p className="text-[10px] text-muted-foreground mt-2">
        Generated by AI — may not capture all details
      </p>
    </div>
  );
}
